#!/bin/sh
ethact eth1

if [ -f /env/ethaddrs ]; then
	. /env/ethaddrs
fi

nand_device="comcertonand"
nand_parts="8M(reserved0),32M(kernel0),32M(kernel1),288M(rootfs0),288M(rootfs1),32M(emergency),-(data+ubi)"

nor_parts="128k(uloader)ro,512k(loader0)ro,512k(loader1)ro,128k(env),2M(hnvram),-(norreserved0)"
nor_device="comcertoflash.0"

autoboot_timeout=2

bootargs="console=ttyS0,115200n8"

if [ -f /env/config.local ]; then
	. /env/config.local
fi
