#!/bin/sh
ethact eth0

if [ -f /env/ethaddrs ]; then
	. /env/ethaddrs
fi

nor_parts="128k(uloader)ro,512k(loader0)ro,512k(loader1)ro,128k(env),2M(hnvram),6M(kernel0),6M(kernel1),-(norreserved0)"
nor_device="comcertoflash.0"

autoboot_timeout=2

bootargs="console=ttyS0,115200n8"

if [ -f /env/config.local ]; then
	. /env/config.local
fi
