#!/bin/sh
ethact eth1

if [ -f /env/ethaddrs ]; then
	. /env/ethaddrs
fi

nor_parts="128k(uloader)ro,512k(loader0)ro,512k(loader1)ro,128k(env),2M(hnvram),6M(kernel0),6M(kernel1),-(norreserved0)"
nor_device="comcertoflash.0"

if [ x${dev_mode} = x0 ]; then
	autoboot_timeout=0
else
	autoboot_timeout=2
fi

if [ x${dev_mode} = x1 ] || [ x${recovery_mode} = x1 ]; then
	bootargs="console=ttyS0,115200n8"
else
	bootargs="console=tty1"
fi

if [ -f /env/config.local ]; then
	. /env/config.local
fi
